# Generated by Django 5.1.3 on 2024-12-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0022_alter_customer_user_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='calorie_goal',
            field=models.IntegerField(default=2000),
        ),
    ]
