# Generated by Django 5.1.3 on 2024-12-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0023_alter_userprofile_calorie_goal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='calorie_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
