# Generated by Django 5.1.3 on 2024-12-03 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0024_alter_customer_calorie_limit'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_intake',
            field=models.FloatField(default=0),
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('meal_type', models.CharField(max_length=100)),
                ('calories', models.IntegerField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Fityfeed.customer')),
            ],
        ),
    ]
