# Generated by Django 5.1.3 on 2024-12-03 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0025_customer_daily_intake_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='activity_level',
            field=models.CharField(choices=[('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High')], default='moderate', max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='calorie_goal',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='goal',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='customer',
            name='height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customer',
            name='weight',
            field=models.FloatField(default=0),
        ),
    ]
