# Generated by Django 5.1.3 on 2024-12-03 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0027_customer_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='daily_intake',
            new_name='calorie_intake',
        ),
    ]
