# Generated by Django 5.1.3 on 2024-12-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0028_rename_daily_intake_customer_calorie_intake'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_intake',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='customer',
            name='calorie_intake',
            field=models.IntegerField(default=0),
        ),
    ]
