# Generated by Django 5.1.3 on 2024-12-03 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0029_customer_daily_intake_alter_customer_calorie_intake'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='carbohydrate',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='category',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='fats',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='protein',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='quantity',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'Breakfast'), ('Lunch', 'Lunch'), ('Snacks', 'Snacks'), ('Dinner', 'Dinner')], default='Breakfast', max_length=50),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='calorie',
            field=models.IntegerField(),
        ),
    ]
