# Generated by Django 5.1.3 on 2024-12-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0034_alter_customer_user_alter_exercise_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='calorie_goal',
            field=models.CharField(choices=[('maintain', 'Maintain'), ('lose', 'Lose Weight'), ('gain', 'Gain Weight')], default='maintain', max_length=100),
        ),
    ]
