# Generated by Django 5.1.3 on 2024-12-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0035_customer_calorie_goal'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='daily_intake',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
