# Generated by Django 5.1.3 on 2024-12-03 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0037_customer_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='calorie_limit',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
