# Generated by Django 5.1.3 on 2024-12-03 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0038_alter_customer_calorie_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='calorie',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='carbohydrate',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='fats',
            field=models.FloatField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='protein',
            field=models.FloatField(default=0, max_length=100),
        ),
    ]
