# Generated by Django 5.1.3 on 2024-12-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0039_remove_fooditem_calorie_fooditem_calories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fooditem',
            name='calories',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
