# Generated by Django 5.1.3 on 2024-12-04 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0041_alter_customer_age_alter_customer_height_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='calorie_needs',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
