# Generated by Django 5.1.3 on 2024-12-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0042_customer_calorie_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='calorie_needs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
