# Generated by Django 5.1.3 on 2024-12-04 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0043_userprofile_calorie_needs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='calorie_needs',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
