# Generated by Django 5.1.3 on 2024-12-05 05:17

import Fityfeed.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0044_alter_customer_calorie_needs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='user',
            field=models.ForeignKey(default=Fityfeed.models.Exercise.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='category',
            field=models.ForeignKey(default=Fityfeed.models.get_default_category, on_delete=django.db.models.deletion.CASCADE, to='Fityfeed.category'),
        ),
        migrations.AlterField(
            model_name='meal',
            name='customer',
            field=models.ForeignKey(default=Fityfeed.models.Meal.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userfooditem',
            name='customer',
            field=models.ForeignKey(default=Fityfeed.models.UserFooditem.get_default_user_id, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
