# Generated by Django 5.1.3 on 2024-12-05 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0045_alter_exercise_user_alter_fooditem_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='time',
            field=models.IntegerField(),
        ),
    ]
