# Generated by Django 5.1.3 on 2024-12-09 08:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Fityfeed', '0050_document'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
